#!/bin/bash



sync_cancel_label="返回"
sync_title="数据同步配置"
sync_backtitle="同步配置"
sync_formtitle="配置项列表"

write_title="保存配置"
write_msg="正在写入配置文件..."


yes="是"
no="否"

sync_msg="BlueBird未安装或安装不正确，无法进行配置!"
sync_radiolist="是否开启数据同步?"
